### ISSUE TITLE
Error upon start up

### ISSUE THREAD

**Issue by davies8172** [dlashua/ewelink-mqtt#3]
I am getting the following message when trying to start up. Can anyone assist? It is a fresh install and myconfig file has been checked.

**node ./index.js -c ./myconfig.js**

*****
/home/pi/ewelink-mqtt/ewelink-mqtt/node_modules/logger/logger.js:98
    this.write(message + "\n");
         ^

TypeError: this.write is not a function
    at Logger.log (/home/pi/ewelink-mqtt/ewelink-mqtt/node_modules/logger/logger.js:98:10)
    at Logger.<computed> [as info] (/home/pi/ewelink-mqtt/ewelink-mqtt/node_modules/logger/logger.js:108:21)
    at new eWeLink (/home/pi/ewelink-mqtt/ewelink-mqtt/node_modules/node-ewelink-cloud/index.js:33:17)
    at Object.<anonymous> (/home/pi/ewelink-mqtt/ewelink-mqtt/index.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
*****

**Comment by kvamvake** [comment]
I have the same issue
